FROM base-image:nx-base AS builder

ARG NODE_ENV
ARG BUILD_FLAG
WORKDIR /app/builder
COPY . .
RUN npx nx build playground-ng-nest ${BUILD_FLAG}

FROM nginx:1.19.2

WORKDIR /usr/share/nginx/html

COPY --from=builder /app/builder/dist/apps/playground-ng-nest ./
COPY --from=builder /app/builder/apps/playground-ng-nest/nginx.conf /etc/nginx/nginx.conf